### ISSUE TITLE
Add option to output SCSS, SASS and LESS for the sprites task

### ISSUE THREAD

**Issue by LaurentGoderre** [asciidisco/grunt-imagine#31]
This would allow to leverage this without being bound to the images filenames

The task output would be:

``` scss
%icon36{
    background: url("../img/icon36.png") no-repeat;
}

%MyImage1 {
    @extend %icons36;
    background-position: 0 -432px;
}

%MyImage2{
    @extend %icons36;
    background-position: 0 -396px;
}
```

Which would allow us to use it like this: 

``` scss
.myclass p .btn {
   @extend: %MyImage1;
}

.myclass2 p {
    @extend: %MyImage2;
}

.myclass3 {
    @extend: %MyImage2;
}
```

Which would output the following:

``` css
.myclass p .btn, .myclass2 p, .myclass3 {
    background: url("../img/icon36.png") no-repeat;
}

.myclass p .btn {
    background-position: 0 -432px;
}

.myclass2 p, .myclass3 {
    background-position: 0 -396px;
}
```
