### ISSUE TITLE
Sprites uses path relative to the grunt root rather than to the CSS output.

### ISSUE THREAD

**Issue by LaurentGoderre** [asciidisco/grunt-imagine#34]
For flexibility, the `background: url()` should be relative to the CSS file not the grunt root.

For example:

``` javascript
sprites:{
    all:{
        src: ["src/plugins/sprites/**/*.png"],
    css: "src/base/partials/_sprites.scss",
    map: "src/base/partials/sprites/sprites.png"
    }
}
```

Results in

``` css
%_sprites_scss {
    background: url("../src/base/partials/sprites/sprites.png") no-repeat;
 }
```

Instead of

``` css
%_sprites_scss {
    background: url("sprites/sprites.png") no-repeat;
 }
```
